//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for algebraicexprtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="algebraicexprtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="algebraicexpr" type="{}setexprtype" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="set" type="{}settype" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="objectref" type="{}objectreftype" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="factref" type="{}factreftype" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="variableref" type="{}variablereftype" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="rulevariableref" type="{}rulevariablereftype" maxOccurs="2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operator" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="add"/>
 *             &lt;enumeration value="diff"/>
 *             &lt;enumeration value="mult"/>
 *             &lt;enumeration value="div"/>
 *             &lt;enumeration value="sqrt"/>
 *             &lt;enumeration value="none"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "algebraicexprtype", propOrder = {
    "algebraicexpr",
    "set",
    "objectref",
    "factref",
    "variableref",
    "rulevariableref"
})
public class Algebraicexprtype {

    protected List<Setexprtype> algebraicexpr;
    protected List<Settype> set;
    protected List<Objectreftype> objectref;
    protected List<Factreftype> factref;
    protected List<Variablereftype> variableref;
    protected List<Rulevariablereftype> rulevariableref;
    @XmlAttribute(name = "operator", required = true)
    protected String operator;

    /**
     * Gets the value of the algebraicexpr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the algebraicexpr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlgebraicexpr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Setexprtype }
     * 
     * 
     */
    public List<Setexprtype> getAlgebraicexpr() {
        if (algebraicexpr == null) {
            algebraicexpr = new ArrayList<Setexprtype>();
        }
        return this.algebraicexpr;
    }

    /**
     * Gets the value of the set property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the set property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Settype }
     * 
     * 
     */
    public List<Settype> getSet() {
        if (set == null) {
            set = new ArrayList<Settype>();
        }
        return this.set;
    }

    /**
     * Gets the value of the objectref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Objectreftype }
     * 
     * 
     */
    public List<Objectreftype> getObjectref() {
        if (objectref == null) {
            objectref = new ArrayList<Objectreftype>();
        }
        return this.objectref;
    }

    /**
     * Gets the value of the factref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the factref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFactref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Factreftype }
     * 
     * 
     */
    public List<Factreftype> getFactref() {
        if (factref == null) {
            factref = new ArrayList<Factreftype>();
        }
        return this.factref;
    }

    /**
     * Gets the value of the variableref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variableref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariableref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Variablereftype }
     * 
     * 
     */
    public List<Variablereftype> getVariableref() {
        if (variableref == null) {
            variableref = new ArrayList<Variablereftype>();
        }
        return this.variableref;
    }

    /**
     * Gets the value of the rulevariableref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rulevariableref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRulevariableref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rulevariablereftype }
     * 
     * 
     */
    public List<Rulevariablereftype> getRulevariableref() {
        if (rulevariableref == null) {
            rulevariableref = new ArrayList<Rulevariablereftype>();
        }
        return this.rulevariableref;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

}
