//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assertexprtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assertexprtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tuple" type="{}tupletype"/>
 *         &lt;element name="support" type="{}supporttype" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="typeref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assertexprtype", propOrder = {
    "tuple",
    "support"
})
public class Assertexprtype {

    @XmlElement(required = true)
    protected Tupletype tuple;
    protected Supporttype support;
    @XmlAttribute(name = "typeref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object typeref;

    /**
     * Gets the value of the tuple property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public Tupletype getTuple() {
        return tuple;
    }

    /**
     * Sets the value of the tuple property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public void setTuple(Tupletype value) {
        this.tuple = value;
    }

    /**
     * Gets the value of the support property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Supporttype }
     *     
     */
    public Supporttype getSupport() {
        return support;
    }

    /**
     * Sets the value of the support property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Supporttype }
     *     
     */
    public void setSupport(Supporttype value) {
        this.support = value;
    }

    /**
     * Gets the value of the typeref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTyperef() {
        return typeref;
    }

    /**
     * Sets the value of the typeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTyperef(Object value) {
        this.typeref = value;
    }

}
