//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assignexprtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assignexprtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="objectref" type="{}objectreftype"/>
 *           &lt;element name="variableref" type="{}variablereftype"/>
 *           &lt;element name="factref" type="{}factreftype"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="tuple" type="{}tupletype"/>
 *           &lt;element name="setexpr" type="{}setexprtype"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignexprtype", propOrder = {
    "objectref",
    "variableref",
    "factref",
    "tuple",
    "setexpr"
})
public class Assignexprtype {

    protected Objectreftype objectref;
    protected Variablereftype variableref;
    protected Factreftype factref;
    protected Tupletype tuple;
    protected Setexprtype setexpr;

    /**
     * Gets the value of the objectref property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Objectreftype }
     *     
     */
    public Objectreftype getObjectref() {
        return objectref;
    }

    /**
     * Sets the value of the objectref property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Objectreftype }
     *     
     */
    public void setObjectref(Objectreftype value) {
        this.objectref = value;
    }

    /**
     * Gets the value of the variableref property.
     * 
     * @return
     *     possible object is
     *     {@link Variablereftype }
     *     
     */
    public Variablereftype getVariableref() {
        return variableref;
    }

    /**
     * Sets the value of the variableref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variablereftype }
     *     
     */
    public void setVariableref(Variablereftype value) {
        this.variableref = value;
    }

    /**
     * Gets the value of the factref property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Factreftype }
     *     
     */
    public Factreftype getFactref() {
        return factref;
    }

    /**
     * Sets the value of the factref property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Factreftype }
     *     
     */
    public void setFactref(Factreftype value) {
        this.factref = value;
    }

    /**
     * Gets the value of the tuple property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public Tupletype getTuple() {
        return tuple;
    }

    /**
     * Sets the value of the tuple property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public void setTuple(Tupletype value) {
        this.tuple = value;
    }

    /**
     * Gets the value of the setexpr property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Setexprtype }
     *     
     */
    public Setexprtype getSetexpr() {
        return setexpr;
    }

    /**
     * Sets the value of the setexpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Setexprtype }
     *     
     */
    public void setSetexpr(Setexprtype value) {
        this.setexpr = value;
    }

}
