//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constraintexprtype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constraintexprtype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="patternexpr" type="{}patternexprtype"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="exists"/>
 *             &lt;enumeration value="not"/>
 *             &lt;enumeration value="forall"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constraintexprtype", propOrder = {
    "patternexpr"
})
public class Constraintexprtype {

    @XmlElement(required = true)
    protected Patternexprtype patternexpr;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the patternexpr property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Patternexprtype }
     *     
     */
    public Patternexprtype getPatternexpr() {
        return patternexpr;
    }

    /**
     * Sets the value of the patternexpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Patternexprtype }
     *     
     */
    public void setPatternexpr(Patternexprtype value) {
        this.patternexpr = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
