//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for facttype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facttype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="facttriple" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="support" type="{}supporttype"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="attributeref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}identifiers"/>
 *       &lt;attribute name="objectref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facttype", propOrder = {
    "facttriple"
})
public class Facttype {

    @XmlElement(required = true)
    protected List<Facttriple> facttriple;
    @XmlAttribute(name = "objectref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object objectref;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the facttriple property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facttriple property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacttriple().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.agh.xsd.Facttype.Facttriple }
     * 
     * 
     */
    public List<Facttriple> getFacttriple() {
        if (facttriple == null) {
            facttriple = new ArrayList<Facttriple>();
        }
        return this.facttriple;
    }

    /**
     * Gets the value of the objectref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getObjectref() {
        return objectref;
    }

    /**
     * Sets the value of the objectref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setObjectref(Object value) {
        this.objectref = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="support" type="{}supporttype"/>
     *       &lt;/sequence>
     *       &lt;attribute name="attributeref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "support"
    })
    public static class Facttriple {

        @XmlElement(required = true)
        protected Supporttype support;
        @XmlAttribute(name = "attributeref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object attributeref;

        /**
         * Gets the value of the support property.
         * 
         * @return
         *     possible object is
         *     {@link Supporttype }
         *     
         */
        public Supporttype getSupport() {
            return support;
        }

        /**
         * Sets the value of the support property.
         * 
         * @param value
         *     allowed object is
         *     {@link Supporttype }
         *     
         */
        public void setSupport(Supporttype value) {
            this.support = value;
        }

        /**
         * Gets the value of the attributeref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAttributeref() {
            return attributeref;
        }

        /**
         * Sets the value of the attributeref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAttributeref(Object value) {
            this.attributeref = value;
        }

    }

}
