//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="types" type="{}typestype"/>
 *         &lt;element name="objects" type="{}objectstype" minOccurs="0"/>
 *         &lt;element name="facts" type="{}factstype" minOccurs="0"/>
 *         &lt;element name="variables" type="{}variablestype" minOccurs="0"/>
 *         &lt;element name="rules" type="{}rulestype"/>
 *         &lt;element name="modules" type="{}modulestype"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "types",
    "objects",
    "facts",
    "variables",
    "rules",
    "modules"
})
@XmlRootElement(name = "model")
public class Model {

    @XmlElement(required = true)
    protected Typestype types;
    protected Objectstype objects;
    protected Factstype facts;
    protected Variablestype variables;
    @XmlElement(required = true)
    protected Rulestype rules;
    @XmlElement(required = true)
    protected Modulestype modules;

    /**
     * Gets the value of the types property.
     * 
     * @return
     *     possible object is
     *     {@link Typestype }
     *     
     */
    public Typestype getTypes() {
        return types;
    }

    /**
     * Sets the value of the types property.
     * 
     * @param value
     *     allowed object is
     *     {@link Typestype }
     *     
     */
    public void setTypes(Typestype value) {
        this.types = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link Objectstype }
     *     
     */
    public Objectstype getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Objectstype }
     *     
     */
    public void setObjects(Objectstype value) {
        this.objects = value;
    }

    /**
     * Gets the value of the facts property.
     * 
     * @return
     *     possible object is
     *     {@link Factstype }
     *     
     */
    public Factstype getFacts() {
        return facts;
    }

    /**
     * Sets the value of the facts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Factstype }
     *     
     */
    public void setFacts(Factstype value) {
        this.facts = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link Variablestype }
     *     
     */
    public Variablestype getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variablestype }
     *     
     */
    public void setVariables(Variablestype value) {
        this.variables = value;
    }

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link Rulestype }
     *     
     */
    public Rulestype getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rulestype }
     *     
     */
    public void setRules(Rulestype value) {
        this.rules = value;
    }

    /**
     * Gets the value of the modules property.
     * 
     * @return
     *     possible object is
     *     {@link Modulestype }
     *     
     */
    public Modulestype getModules() {
        return modules;
    }

    /**
     * Sets the value of the modules property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modulestype }
     *     
     */
    public void setModules(Modulestype value) {
        this.modules = value;
    }

}
