//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.edu.agh.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.edu.agh.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype }
     * 
     */
    public Ruletype createRuletype() {
        return new Ruletype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype.Rulevariables }
     * 
     */
    public Ruletype.Rulevariables createRuletypeRulevariables() {
        return new Ruletype.Rulevariables();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Tupletype }
     * 
     */
    public Tupletype createTupletype() {
        return new Tupletype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Facttype }
     * 
     */
    public Facttype createFacttype() {
        return new Facttype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Supporttype }
     * 
     */
    public Supporttype createSupporttype() {
        return new Supporttype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Supporttype.Sgroup }
     * 
     */
    public Supporttype.Sgroup createSupporttypeSgroup() {
        return new Supporttype.Sgroup();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Settype }
     * 
     */
    public Settype createSettype() {
        return new Settype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Moduletype }
     * 
     */
    public Moduletype createModuletype() {
        return new Moduletype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Typetype }
     * 
     */
    public Typetype createTypetype() {
        return new Typetype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Typestype }
     * 
     */
    public Typestype createTypestype() {
        return new Typestype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Objectstype }
     * 
     */
    public Objectstype createObjectstype() {
        return new Objectstype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Factstype }
     * 
     */
    public Factstype createFactstype() {
        return new Factstype();
    }

    /**
     * Create an instance of {@link Variablestype }
     * 
     */
    public Variablestype createVariablestype() {
        return new Variablestype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Rulestype }
     * 
     */
    public Rulestype createRulestype() {
        return new Rulestype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Modulestype }
     * 
     */
    public Modulestype createModulestype() {
        return new Modulestype();
    }

    /**
     * Create an instance of {@link Algebraicexprtype }
     * 
     */
    public Algebraicexprtype createAlgebraicexprtype() {
        return new Algebraicexprtype();
    }

    /**
     * Create an instance of {@link Variablereftype }
     * 
     */
    public Variablereftype createVariablereftype() {
        return new Variablereftype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Variabletype }
     * 
     */
    public Variabletype createVariabletype() {
        return new Variabletype();
    }

    /**
     * Create an instance of {@link Assertexprtype }
     * 
     */
    public Assertexprtype createAssertexprtype() {
        return new Assertexprtype();
    }

    /**
     * Create an instance of {@link Rulevariablereftype }
     * 
     */
    public Rulevariablereftype createRulevariablereftype() {
        return new Rulevariablereftype();
    }

    /**
     * Create an instance of {@link Retractexprtype }
     * 
     */
    public Retractexprtype createRetractexprtype() {
        return new Retractexprtype();
    }

    /**
     * Create an instance of {@link Logicalexprtype }
     * 
     */
    public Logicalexprtype createLogicalexprtype() {
        return new Logicalexprtype();
    }

    /**
     * Create an instance of {@link Constraintexprtype }
     * 
     */
    public Constraintexprtype createConstraintexprtype() {
        return new Constraintexprtype();
    }

    /**
     * Create an instance of {@link Objectreftype }
     * 
     */
    public Objectreftype createObjectreftype() {
        return new Objectreftype();
    }

    /**
     * Create an instance of {@link Submoduletype }
     * 
     */
    public Submoduletype createSubmoduletype() {
        return new Submoduletype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Factreftype }
     * 
     */
    public Factreftype createFactreftype() {
        return new Factreftype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Objecttype }
     * 
     */
    public Objecttype createObjecttype() {
        return new Objecttype();
    }

    /**
     * Create an instance of {@link Patternexprtype }
     * 
     */
    public Patternexprtype createPatternexprtype() {
        return new Patternexprtype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Rulereftype }
     * 
     */
    public Rulereftype createRulereftype() {
        return new Rulereftype();
    }

    /**
     * Create an instance of {@link Assignexprtype }
     * 
     */
    public Assignexprtype createAssignexprtype() {
        return new Assignexprtype();
    }

    /**
     * Create an instance of {@link Relationexprtype }
     * 
     */
    public Relationexprtype createRelationexprtype() {
        return new Relationexprtype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Setexprtype }
     * 
     */
    public Setexprtype createSetexprtype() {
        return new Setexprtype();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype.Lhs }
     * 
     */
    public Ruletype.Lhs createRuletypeLhs() {
        return new Ruletype.Lhs();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype.Rhs }
     * 
     */
    public Ruletype.Rhs createRuletypeRhs() {
        return new Ruletype.Rhs();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype.Scope }
     * 
     */
    public Ruletype.Scope createRuletypeScope() {
        return new Ruletype.Scope();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Ruletype.Rulevariables.Rulevariable }
     * 
     */
    public Ruletype.Rulevariables.Rulevariable createRuletypeRulevariablesRulevariable() {
        return new Ruletype.Rulevariables.Rulevariable();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Tupletype.Item }
     * 
     */
    public Tupletype.Item createTupletypeItem() {
        return new Tupletype.Item();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Facttype.Facttriple }
     * 
     */
    public Facttype.Facttriple createFacttypeFacttriple() {
        return new Facttype.Facttriple();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Supporttype.Sgroup.Facttripleref }
     * 
     */
    public Supporttype.Sgroup.Facttripleref createSupporttypeSgroupFacttripleref() {
        return new Supporttype.Sgroup.Facttripleref();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Settype.Range }
     * 
     */
    public Settype.Range createSettypeRange() {
        return new Settype.Range();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Moduletype.Xormodule }
     * 
     */
    public Moduletype.Xormodule createModuletypeXormodule() {
        return new Moduletype.Xormodule();
    }

    /**
     * Create an instance of {@link pl.edu.agh.xsd.Typetype.Attribute }
     * 
     */
    public Typetype.Attribute createTypetypeAttribute() {
        return new Typetype.Attribute();
    }

}
