//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ruletype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruletype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rulevariables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rulevariable">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attGroup ref="{}identifiers"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lhs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="patternexpr" type="{}patternexprtype" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="constraintexpr" type="{}constraintexprtype" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rhs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="assertexpr" type="{}assertexprtype" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="retractexpr" type="{}retractexprtype" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="assignexpr" type="{}assignexprtype" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="scope">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="noloop"/>
 *                       &lt;enumeration value="goto"/>
 *                       &lt;enumeration value="terminate"/>
 *                       &lt;enumeration value="none"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="moduleref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}identifiers"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruletype", propOrder = {
    "rulevariables",
    "lhs",
    "rhs",
    "scope"
})
public class Ruletype {

    protected Rulevariables rulevariables;
    protected Lhs lhs;
    @XmlElement(required = true)
    protected Rhs rhs;
    @XmlElement(required = true)
    protected Scope scope;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the rulevariables property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Ruletype.Rulevariables }
     *     
     */
    public Rulevariables getRulevariables() {
        return rulevariables;
    }

    /**
     * Sets the value of the rulevariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Ruletype.Rulevariables }
     *     
     */
    public void setRulevariables(Rulevariables value) {
        this.rulevariables = value;
    }

    /**
     * Gets the value of the lhs property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Ruletype.Lhs }
     *     
     */
    public Lhs getLhs() {
        return lhs;
    }

    /**
     * Sets the value of the lhs property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Ruletype.Lhs }
     *     
     */
    public void setLhs(Lhs value) {
        this.lhs = value;
    }

    /**
     * Gets the value of the rhs property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Ruletype.Rhs }
     *     
     */
    public Rhs getRhs() {
        return rhs;
    }

    /**
     * Sets the value of the rhs property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Ruletype.Rhs }
     *     
     */
    public void setRhs(Rhs value) {
        this.rhs = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Ruletype.Scope }
     *     
     */
    public Scope getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Ruletype.Scope }
     *     
     */
    public void setScope(Scope value) {
        this.scope = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="patternexpr" type="{}patternexprtype" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="constraintexpr" type="{}constraintexprtype" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "patternexpr",
        "constraintexpr"
    })
    public static class Lhs {

        protected List<Patternexprtype> patternexpr;
        protected List<Constraintexprtype> constraintexpr;

        /**
         * Gets the value of the patternexpr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the patternexpr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPatternexpr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Patternexprtype }
         * 
         * 
         */
        public List<Patternexprtype> getPatternexpr() {
            if (patternexpr == null) {
                patternexpr = new ArrayList<Patternexprtype>();
            }
            return this.patternexpr;
        }

        /**
         * Gets the value of the constraintexpr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the constraintexpr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConstraintexpr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Constraintexprtype }
         * 
         * 
         */
        public List<Constraintexprtype> getConstraintexpr() {
            if (constraintexpr == null) {
                constraintexpr = new ArrayList<Constraintexprtype>();
            }
            return this.constraintexpr;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="assertexpr" type="{}assertexprtype" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="retractexpr" type="{}retractexprtype" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="assignexpr" type="{}assignexprtype" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assertexpr",
        "retractexpr",
        "assignexpr"
    })
    public static class Rhs {

        protected List<Assertexprtype> assertexpr;
        protected List<Retractexprtype> retractexpr;
        protected List<Assignexprtype> assignexpr;

        /**
         * Gets the value of the assertexpr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assertexpr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssertexpr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Assertexprtype }
         * 
         * 
         */
        public List<Assertexprtype> getAssertexpr() {
            if (assertexpr == null) {
                assertexpr = new ArrayList<Assertexprtype>();
            }
            return this.assertexpr;
        }

        /**
         * Gets the value of the retractexpr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the retractexpr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRetractexpr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Retractexprtype }
         * 
         * 
         */
        public List<Retractexprtype> getRetractexpr() {
            if (retractexpr == null) {
                retractexpr = new ArrayList<Retractexprtype>();
            }
            return this.retractexpr;
        }

        /**
         * Gets the value of the assignexpr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assignexpr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssignexpr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Assignexprtype }
         * 
         * 
         */
        public List<Assignexprtype> getAssignexpr() {
            if (assignexpr == null) {
                assignexpr = new ArrayList<Assignexprtype>();
            }
            return this.assignexpr;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rulevariable">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attGroup ref="{}identifiers"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rulevariable"
    })
    public static class Rulevariables {

        @XmlElement(required = true)
        protected Rulevariable rulevariable;

        /**
         * Gets the value of the rulevariable property.
         * 
         * @return
         *     possible object is
         *     {@link pl.edu.agh.xsd.Ruletype.Rulevariables.Rulevariable }
         *     
         */
        public Rulevariable getRulevariable() {
            return rulevariable;
        }

        /**
         * Sets the value of the rulevariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link pl.edu.agh.xsd.Ruletype.Rulevariables.Rulevariable }
         *     
         */
        public void setRulevariable(Rulevariable value) {
            this.rulevariable = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attGroup ref="{}identifiers"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Rulevariable {

            @XmlAttribute(name = "id", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String id;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="noloop"/>
     *             &lt;enumeration value="goto"/>
     *             &lt;enumeration value="terminate"/>
     *             &lt;enumeration value="none"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="moduleref" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Scope {

        @XmlAttribute(name = "type", required = true)
        protected String type;
        @XmlAttribute(name = "moduleref")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object moduleref;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the moduleref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getModuleref() {
            return moduleref;
        }

        /**
         * Sets the value of the moduleref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setModuleref(Object value) {
            this.moduleref = value;
        }

    }

}
