//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.28 at 11:13:34 AM CET 
//


package pl.edu.agh.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for variabletype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variabletype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="tuple" type="{}tupletype"/>
 *         &lt;element name="set" type="{}settype"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}identifiers"/>
 *       &lt;attribute name="typeref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variabletype", propOrder = {
    "tuple",
    "set"
})
public class Variabletype {

    protected Tupletype tuple;
    protected Settype set;
    @XmlAttribute(name = "typeref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object typeref;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the tuple property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public Tupletype getTuple() {
        return tuple;
    }

    /**
     * Sets the value of the tuple property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Tupletype }
     *     
     */
    public void setTuple(Tupletype value) {
        this.tuple = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link pl.edu.agh.xsd.Settype }
     *     
     */
    public Settype getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link pl.edu.agh.xsd.Settype }
     *     
     */
    public void setSet(Settype value) {
        this.set = value;
    }

    /**
     * Gets the value of the typeref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTyperef() {
        return typeref;
    }

    /**
     * Sets the value of the typeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTyperef(Object value) {
        this.typeref = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
